/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Samuel
 */
import java.awt.*;
import javax.swing.*;
//new code
import javax.sound.sampled.*;
import java.net.URL;
import java.io.*;
public class SecondWind extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    int ctr=0;
    public SecondWind() {
        initComponents();
        pnlTutorial.setVisible(false);
        pnlIntro.setVisible(false);
        lblIntro2.setVisible(false);
        lblIntro3.setVisible(false);
        lblIntro4.setVisible(false);
        lblIntro5.setVisible(false);
        lblIntro6.setVisible(false);
        lblIntro7.setVisible(false);
        lblAssassin.setVisible(false);
        lblIconAssassin.setVisible(false);
        pnlChapter1Hallway.setVisible(false);
        lblChapter1E.setVisible(false);
        lblMonster.setVisible(false);
        lblAssassin1.setVisible(false);
        lblIconAssassin1.setVisible(false);
        lblMonster1.setVisible(false);
        lblAssassin2.setVisible(false);
        lblIconAssassin2.setVisible(false);
        pnlChapter2Elevator.setVisible(false);
        lblChapter2Hallway.setVisible(false);
        lblFamilliar.setVisible(false);
        lblAssassin3.setVisible(false);
        lblShielderAlter.setVisible(false);
        lblShielderAlterMark.setVisible(false);
        pnlChapter2Hallway.setVisible(false);
        lblChapter2Hallway1.setVisible(false);
        lblMageAlter.setVisible(false);
        pnlChapter3Stair.setVisible(false);
        lblAssassin4.setVisible(false);
        lblMageAlter1.setVisible(false);
    }
    
    public void printL(String line){
        for (int i=0;i<line.length();i++){
            txtDialogue.setText(String.valueOf(line.charAt(i)));
        }
    }
    void playMusic(String filepath){
        try{
            File file = new File(filepath);
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(file);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            //clip.loop(1);//Clip.LOOP_CONTINUOUSLY
            clip.start();
        }
        catch(Exception E){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChapter3Stair = new javax.swing.JPanel();
        btnNext4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDialogue5 = new javax.swing.JTextArea();
        lblDialogueBox5 = new javax.swing.JLabel();
        lblMageAlter1 = new javax.swing.JLabel();
        lblAssassin5 = new javax.swing.JLabel();
        lblChapter2Hallway2 = new javax.swing.JLabel();
        lblChapter2Stairs = new javax.swing.JLabel();
        pnlChapter2Hallway = new javax.swing.JPanel();
        btnNext3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDialogue4 = new javax.swing.JTextArea();
        lblDialogueBox4 = new javax.swing.JLabel();
        lblMageAlter = new javax.swing.JLabel();
        lblAssassin4 = new javax.swing.JLabel();
        lblChapter2Hallway1 = new javax.swing.JLabel();
        pnlChapter2Elevator = new javax.swing.JPanel();
        btnNext2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDialogue3 = new javax.swing.JTextArea();
        lblDialogueBox3 = new javax.swing.JLabel();
        lblShielderAlterMark = new javax.swing.JLabel();
        lblShielderAlter = new javax.swing.JLabel();
        lblAssassin3 = new javax.swing.JLabel();
        lblFamilliar = new javax.swing.JLabel();
        lblChapter2Hallway = new javax.swing.JLabel();
        lblChapter2Elevator = new javax.swing.JLabel();
        pnlChapter1Elevator = new javax.swing.JPanel();
        btnNext1 = new javax.swing.JButton();
        lblIconAssassin2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDialogue2 = new javax.swing.JTextArea();
        lblDialogueBox2 = new javax.swing.JLabel();
        lblAssassin2 = new javax.swing.JLabel();
        lblMonster1 = new javax.swing.JLabel();
        lblChapter1Elevator = new javax.swing.JLabel();
        pnlChapter1Hallway = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        lblIconAssassin1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDialogue1 = new javax.swing.JTextArea();
        lblDialogueBox1 = new javax.swing.JLabel();
        lblAssassin1 = new javax.swing.JLabel();
        lblMonster = new javax.swing.JLabel();
        lblChapter1E = new javax.swing.JLabel();
        pnlIntro = new javax.swing.JPanel();
        btnPlay1 = new javax.swing.JButton();
        lblIconAssassin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDialogue = new javax.swing.JTextArea();
        lblDialogueBox = new javax.swing.JLabel();
        lblAssassin = new javax.swing.JLabel();
        lblIntro7 = new javax.swing.JLabel();
        lblIntro6 = new javax.swing.JLabel();
        lblIntro5 = new javax.swing.JLabel();
        lblIntro4 = new javax.swing.JLabel();
        lblIntro3 = new javax.swing.JLabel();
        lblIntro2 = new javax.swing.JLabel();
        lblIntro1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnHighScore = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblColumnL = new javax.swing.JLabel();
        lblColumnR = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        pnlTutorial = new javax.swing.JPanel();
        pnlTLayout = new javax.swing.JPanel();
        lblNameE = new javax.swing.JLabel();
        lblEnemyBorder = new javax.swing.JLabel();
        lblEnemyAvatar = new javax.swing.JLabel();
        lblHPBarE = new javax.swing.JLabel();
        pbEnemyHP = new javax.swing.JProgressBar();
        lblNameP = new javax.swing.JLabel();
        lblPlayerBorder = new javax.swing.JLabel();
        lblPlayerAvatar = new javax.swing.JLabel();
        lblHPBarP = new javax.swing.JLabel();
        pbPlayerHP = new javax.swing.JProgressBar();
        btnAttack = new javax.swing.JButton();
        btnDefend = new javax.swing.JButton();
        btnBag = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblBattleUI = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblTutorialBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Second Wind");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("SecondWind"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        pnlChapter3Stair.setBackground(new java.awt.Color(25, 25, 25));
        pnlChapter3Stair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChapter3Stair.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlChapter3Stair.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlChapter3Stair.setLayout(null);

        btnNext4.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnNext4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnNext4.setText("Next");
        btnNext4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext4.setMaximumSize(new java.awt.Dimension(100, 40));
        btnNext4.setMinimumSize(new java.awt.Dimension(100, 40));
        btnNext4.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnNext4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext4ActionPerformed(evt);
            }
        });
        pnlChapter3Stair.add(btnNext4);
        btnNext4.setBounds(1140, 620, 100, 40);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDialogue5.setBackground(new java.awt.Color(250, 235, 215));
        txtDialogue5.setColumns(20);
        txtDialogue5.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        txtDialogue5.setForeground(new java.awt.Color(188, 132, 29));
        txtDialogue5.setRows(5);
        jScrollPane6.setViewportView(txtDialogue5);

        pnlChapter3Stair.add(jScrollPane6);
        jScrollPane6.setBounds(200, 580, 910, 90);

        lblDialogueBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/dialogue_box.png"))); // NOI18N
        pnlChapter3Stair.add(lblDialogueBox5);
        lblDialogueBox5.setBounds(20, 540, 1236, 162);

        lblMageAlter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Mage Alter.png"))); // NOI18N
        pnlChapter3Stair.add(lblMageAlter1);
        lblMageAlter1.setBounds(360, 60, 630, 673);

        lblAssassin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Assassin.png"))); // NOI18N
        pnlChapter3Stair.add(lblAssassin5);
        lblAssassin5.setBounds(480, 60, 382, 666);

        lblChapter2Hallway2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/hallway_2.png"))); // NOI18N
        pnlChapter3Stair.add(lblChapter2Hallway2);
        lblChapter2Hallway2.setBounds(0, 0, 1280, 720);

        lblChapter2Stairs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/elevator.png"))); // NOI18N
        pnlChapter3Stair.add(lblChapter2Stairs);
        lblChapter2Stairs.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlChapter3Stair);
        pnlChapter3Stair.setBounds(0, 0, 1280, 720);

        pnlChapter2Hallway.setBackground(new java.awt.Color(25, 25, 25));
        pnlChapter2Hallway.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChapter2Hallway.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlChapter2Hallway.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlChapter2Hallway.setLayout(null);

        btnNext3.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnNext3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnNext3.setText("Next");
        btnNext3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext3.setMaximumSize(new java.awt.Dimension(100, 40));
        btnNext3.setMinimumSize(new java.awt.Dimension(100, 40));
        btnNext3.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnNext3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext3ActionPerformed(evt);
            }
        });
        pnlChapter2Hallway.add(btnNext3);
        btnNext3.setBounds(1140, 620, 100, 40);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDialogue4.setBackground(new java.awt.Color(250, 235, 215));
        txtDialogue4.setColumns(20);
        txtDialogue4.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        txtDialogue4.setForeground(new java.awt.Color(188, 132, 29));
        txtDialogue4.setRows(5);
        jScrollPane5.setViewportView(txtDialogue4);

        pnlChapter2Hallway.add(jScrollPane5);
        jScrollPane5.setBounds(200, 580, 910, 90);

        lblDialogueBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/dialogue_box.png"))); // NOI18N
        pnlChapter2Hallway.add(lblDialogueBox4);
        lblDialogueBox4.setBounds(20, 540, 1236, 162);

        lblMageAlter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Mage Alter.png"))); // NOI18N
        pnlChapter2Hallway.add(lblMageAlter);
        lblMageAlter.setBounds(360, 60, 630, 673);

        lblAssassin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Assassin.png"))); // NOI18N
        pnlChapter2Hallway.add(lblAssassin4);
        lblAssassin4.setBounds(480, 60, 382, 666);

        lblChapter2Hallway1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/hallway_2.png"))); // NOI18N
        pnlChapter2Hallway.add(lblChapter2Hallway1);
        lblChapter2Hallway1.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlChapter2Hallway);
        pnlChapter2Hallway.setBounds(0, 0, 1280, 720);

        pnlChapter2Elevator.setBackground(new java.awt.Color(25, 25, 25));
        pnlChapter2Elevator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChapter2Elevator.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlChapter2Elevator.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlChapter2Elevator.setLayout(null);

        btnNext2.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnNext2.setText("Next");
        btnNext2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext2.setMaximumSize(new java.awt.Dimension(100, 40));
        btnNext2.setMinimumSize(new java.awt.Dimension(100, 40));
        btnNext2.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnNext2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });
        pnlChapter2Elevator.add(btnNext2);
        btnNext2.setBounds(1140, 620, 100, 40);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDialogue3.setBackground(new java.awt.Color(250, 235, 215));
        txtDialogue3.setColumns(20);
        txtDialogue3.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        txtDialogue3.setForeground(new java.awt.Color(188, 132, 29));
        txtDialogue3.setRows(5);
        jScrollPane4.setViewportView(txtDialogue3);

        pnlChapter2Elevator.add(jScrollPane4);
        jScrollPane4.setBounds(200, 580, 910, 90);

        lblDialogueBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/dialogue_box.png"))); // NOI18N
        pnlChapter2Elevator.add(lblDialogueBox3);
        lblDialogueBox3.setBounds(20, 540, 1236, 162);

        lblShielderAlterMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/shielder_alter_zoom.png"))); // NOI18N
        lblShielderAlterMark.setMaximumSize(new java.awt.Dimension(1280, 121));
        lblShielderAlterMark.setMinimumSize(new java.awt.Dimension(1280, 121));
        lblShielderAlterMark.setPreferredSize(new java.awt.Dimension(1280, 121));
        pnlChapter2Elevator.add(lblShielderAlterMark);
        lblShielderAlterMark.setBounds(0, 190, 1280, 121);

        lblShielderAlter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Shielder Alter.png"))); // NOI18N
        pnlChapter2Elevator.add(lblShielderAlter);
        lblShielderAlter.setBounds(390, 50, 460, 673);

        lblAssassin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Assassin.png"))); // NOI18N
        pnlChapter2Elevator.add(lblAssassin3);
        lblAssassin3.setBounds(480, 60, 382, 666);

        lblFamilliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/familliar.png"))); // NOI18N
        pnlChapter2Elevator.add(lblFamilliar);
        lblFamilliar.setBounds(80, 20, 1100, 720);

        lblChapter2Hallway.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/hallway_2.png"))); // NOI18N
        pnlChapter2Elevator.add(lblChapter2Hallway);
        lblChapter2Hallway.setBounds(0, 0, 1280, 720);

        lblChapter2Elevator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/elevator.png"))); // NOI18N
        pnlChapter2Elevator.add(lblChapter2Elevator);
        lblChapter2Elevator.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlChapter2Elevator);
        pnlChapter2Elevator.setBounds(0, 0, 1280, 720);

        pnlChapter1Elevator.setBackground(new java.awt.Color(25, 25, 25));
        pnlChapter1Elevator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChapter1Elevator.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlChapter1Elevator.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlChapter1Elevator.setLayout(null);

        btnNext1.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnNext1.setText("Next");
        btnNext1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext1.setMaximumSize(new java.awt.Dimension(100, 40));
        btnNext1.setMinimumSize(new java.awt.Dimension(100, 40));
        btnNext1.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnNext1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        pnlChapter1Elevator.add(btnNext1);
        btnNext1.setBounds(1140, 620, 100, 40);

        lblIconAssassin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/assassin_icon.png"))); // NOI18N
        pnlChapter1Elevator.add(lblIconAssassin2);
        lblIconAssassin2.setBounds(50, 570, 109, 111);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDialogue2.setBackground(new java.awt.Color(250, 235, 215));
        txtDialogue2.setColumns(20);
        txtDialogue2.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        txtDialogue2.setForeground(new java.awt.Color(188, 132, 29));
        txtDialogue2.setRows(5);
        jScrollPane3.setViewportView(txtDialogue2);

        pnlChapter1Elevator.add(jScrollPane3);
        jScrollPane3.setBounds(200, 580, 910, 90);

        lblDialogueBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/dialogue_box.png"))); // NOI18N
        pnlChapter1Elevator.add(lblDialogueBox2);
        lblDialogueBox2.setBounds(20, 540, 1236, 162);

        lblAssassin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Assassin.png"))); // NOI18N
        pnlChapter1Elevator.add(lblAssassin2);
        lblAssassin2.setBounds(480, 60, 382, 666);

        lblMonster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/monster_1.png"))); // NOI18N
        pnlChapter1Elevator.add(lblMonster1);
        lblMonster1.setBounds(200, 0, 850, 720);

        lblChapter1Elevator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/hallway.png"))); // NOI18N
        pnlChapter1Elevator.add(lblChapter1Elevator);
        lblChapter1Elevator.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlChapter1Elevator);
        pnlChapter1Elevator.setBounds(0, 0, 1280, 720);

        pnlChapter1Hallway.setBackground(new java.awt.Color(25, 25, 25));
        pnlChapter1Hallway.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChapter1Hallway.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlChapter1Hallway.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlChapter1Hallway.setLayout(null);

        btnNext.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnNext.setText("Next");
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.setMaximumSize(new java.awt.Dimension(100, 40));
        btnNext.setMinimumSize(new java.awt.Dimension(100, 40));
        btnNext.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnNext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlChapter1Hallway.add(btnNext);
        btnNext.setBounds(1140, 620, 100, 40);

        lblIconAssassin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/assassin_icon.png"))); // NOI18N
        pnlChapter1Hallway.add(lblIconAssassin1);
        lblIconAssassin1.setBounds(50, 570, 109, 111);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDialogue1.setBackground(new java.awt.Color(250, 235, 215));
        txtDialogue1.setColumns(20);
        txtDialogue1.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        txtDialogue1.setForeground(new java.awt.Color(188, 132, 29));
        txtDialogue1.setRows(5);
        jScrollPane2.setViewportView(txtDialogue1);

        pnlChapter1Hallway.add(jScrollPane2);
        jScrollPane2.setBounds(200, 580, 910, 90);

        lblDialogueBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/dialogue_box.png"))); // NOI18N
        pnlChapter1Hallway.add(lblDialogueBox1);
        lblDialogueBox1.setBounds(20, 540, 1236, 162);

        lblAssassin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Assassin.png"))); // NOI18N
        pnlChapter1Hallway.add(lblAssassin1);
        lblAssassin1.setBounds(480, 60, 382, 666);

        lblMonster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/monster_1.png"))); // NOI18N
        pnlChapter1Hallway.add(lblMonster);
        lblMonster.setBounds(200, 0, 850, 720);

        lblChapter1E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/hallway_elevator.png"))); // NOI18N
        pnlChapter1Hallway.add(lblChapter1E);
        lblChapter1E.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlChapter1Hallway);
        pnlChapter1Hallway.setBounds(0, 0, 1280, 720);

        pnlIntro.setBackground(new java.awt.Color(25, 25, 25));
        pnlIntro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlIntro.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlIntro.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlIntro.setLayout(null);

        btnPlay1.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnPlay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnPlay1.setText("Next");
        btnPlay1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay1.setMaximumSize(new java.awt.Dimension(100, 40));
        btnPlay1.setMinimumSize(new java.awt.Dimension(100, 40));
        btnPlay1.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPlay1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnPlay1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlay1ActionPerformed(evt);
            }
        });
        pnlIntro.add(btnPlay1);
        btnPlay1.setBounds(1140, 620, 100, 40);

        lblIconAssassin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/assassin_icon.png"))); // NOI18N
        lblIconAssassin.setMaximumSize(new java.awt.Dimension(109, 111));
        lblIconAssassin.setMinimumSize(new java.awt.Dimension(109, 111));
        lblIconAssassin.setPreferredSize(new java.awt.Dimension(109, 111));
        pnlIntro.add(lblIconAssassin);
        lblIconAssassin.setBounds(50, 570, 109, 111);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDialogue.setBackground(new java.awt.Color(250, 235, 215));
        txtDialogue.setColumns(20);
        txtDialogue.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        txtDialogue.setForeground(new java.awt.Color(188, 132, 29));
        txtDialogue.setRows(5);
        jScrollPane1.setViewportView(txtDialogue);

        pnlIntro.add(jScrollPane1);
        jScrollPane1.setBounds(200, 580, 910, 90);

        lblDialogueBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/dialogue_box.png"))); // NOI18N
        pnlIntro.add(lblDialogueBox);
        lblDialogueBox.setBounds(20, 540, 1236, 162);

        lblAssassin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Character/Assassin.png"))); // NOI18N
        lblAssassin.setMaximumSize(new java.awt.Dimension(382, 666));
        lblAssassin.setMinimumSize(new java.awt.Dimension(382, 666));
        lblAssassin.setPreferredSize(new java.awt.Dimension(382, 666));
        pnlIntro.add(lblAssassin);
        lblAssassin.setBounds(480, 60, 382, 666);

        lblIntro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/gate.png"))); // NOI18N
        pnlIntro.add(lblIntro7);
        lblIntro7.setBounds(0, 0, 1280, 720);

        lblIntro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/ruined_city.png"))); // NOI18N
        pnlIntro.add(lblIntro6);
        lblIntro6.setBounds(0, 0, 1280, 720);

        lblIntro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/Black.png"))); // NOI18N
        pnlIntro.add(lblIntro5);
        lblIntro5.setBounds(0, 0, 1280, 720);

        lblIntro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/death.png"))); // NOI18N
        lblIntro4.setMaximumSize(new java.awt.Dimension(1280, 720));
        lblIntro4.setMinimumSize(new java.awt.Dimension(1280, 720));
        lblIntro4.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlIntro.add(lblIntro4);
        lblIntro4.setBounds(0, 0, 1280, 720);

        lblIntro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/shine.png"))); // NOI18N
        lblIntro3.setMaximumSize(new java.awt.Dimension(1280, 720));
        lblIntro3.setMinimumSize(new java.awt.Dimension(1280, 720));
        lblIntro3.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlIntro.add(lblIntro3);
        lblIntro3.setBounds(0, 0, 1280, 720);

        lblIntro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/three_heroes.png"))); // NOI18N
        lblIntro2.setMaximumSize(new java.awt.Dimension(1280, 720));
        lblIntro2.setMinimumSize(new java.awt.Dimension(1280, 720));
        lblIntro2.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlIntro.add(lblIntro2);
        lblIntro2.setBounds(0, 0, 1280, 720);

        lblIntro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dialogue/Backgrounds/light.png"))); // NOI18N
        pnlIntro.add(lblIntro1);
        lblIntro1.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlIntro);
        pnlIntro.setBounds(0, 0, 1280, 720);

        pnlMain.setBackground(new java.awt.Color(33, 19, 13));
        pnlMain.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlMain.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlMain.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(135, 62, 35));
        pnlMenu.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlMenu.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlMenu.setOpaque(false);
        pnlMenu.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlMenu.setLayout(null);

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SecondWindLogo.png"))); // NOI18N
        lblLogo1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        pnlMenu.add(lblLogo1);
        lblLogo1.setBounds(380, 60, 500, 222);

        btnPlay.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnPlay.setText("Play");
        btnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay.setMaximumSize(new java.awt.Dimension(100, 40));
        btnPlay.setMinimumSize(new java.awt.Dimension(100, 40));
        btnPlay.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPlay);
        btnPlay.setBounds(580, 340, 100, 40);

        btnHighScore.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnHighScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnHighScore.setText("Score");
        btnHighScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHighScore.setMaximumSize(new java.awt.Dimension(100, 40));
        btnHighScore.setMinimumSize(new java.awt.Dimension(100, 40));
        btnHighScore.setPreferredSize(new java.awt.Dimension(100, 40));
        btnHighScore.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnHighScore.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnHighScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoreActionPerformed(evt);
            }
        });
        pnlMenu.add(btnHighScore);
        btnHighScore.setBounds(580, 400, 100, 40);

        btnExit.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_up.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMaximumSize(new java.awt.Dimension(100, 40));
        btnExit.setMinimumSize(new java.awt.Dimension(100, 40));
        btnExit.setPreferredSize(new java.awt.Dimension(100, 40));
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_hover.png"))); // NOI18N
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_down.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlMenu.add(btnExit);
        btnExit.setBounds(580, 460, 100, 40);

        lblColumnL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Column.png"))); // NOI18N
        pnlMenu.add(lblColumnL);
        lblColumnL.setBounds(1110, 0, 168, 720);

        lblColumnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Column.png"))); // NOI18N
        pnlMenu.add(lblColumnR);
        lblColumnR.setBounds(0, 0, 168, 720);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EpicBG.gif"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(1080, 720));
        lblBackground.setMinimumSize(new java.awt.Dimension(1080, 720));
        lblBackground.setPreferredSize(new java.awt.Dimension(1080, 720));
        pnlMenu.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        pnlMain.add(pnlMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain);
        pnlMain.setBounds(0, 0, 1280, 720);

        pnlTutorial.setBackground(new java.awt.Color(25, 25, 25));
        pnlTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlTutorial.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlTutorial.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlTutorial.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlTutorial.setLayout(new java.awt.BorderLayout());

        pnlTLayout.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlTLayout.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlTLayout.setOpaque(false);
        pnlTLayout.setLayout(null);

        lblNameE.setFont(new java.awt.Font("Joystix Monospace", 0, 18)); // NOI18N
        lblNameE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameE.setText("Enemy");
        lblNameE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNameE.setMaximumSize(new java.awt.Dimension(110, 20));
        lblNameE.setMinimumSize(new java.awt.Dimension(110, 20));
        lblNameE.setPreferredSize(new java.awt.Dimension(110, 20));
        lblNameE.setRequestFocusEnabled(false);
        pnlTLayout.add(lblNameE);
        lblNameE.setBounds(1090, 660, 110, 20);

        lblEnemyBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BattleUI_EnemyBorder.png"))); // NOI18N
        pnlTLayout.add(lblEnemyBorder);
        lblEnemyBorder.setBounds(1070, 500, 150, 150);

        lblEnemyAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlaceHolder_PlayeAvatar.png"))); // NOI18N
        lblEnemyAvatar.setMaximumSize(new java.awt.Dimension(110, 110));
        lblEnemyAvatar.setMinimumSize(new java.awt.Dimension(110, 110));
        lblEnemyAvatar.setPreferredSize(new java.awt.Dimension(110, 110));
        pnlTLayout.add(lblEnemyAvatar);
        lblEnemyAvatar.setBounds(1090, 520, 110, 110);

        lblHPBarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BattleUI_PlayerHP.png"))); // NOI18N
        pnlTLayout.add(lblHPBarE);
        lblHPBarE.setBounds(1070, 460, 150, 32);

        pbEnemyHP.setBackground(new java.awt.Color(255, 255, 255));
        pbEnemyHP.setFont(new java.awt.Font("Joystix Monospace", 0, 10)); // NOI18N
        pbEnemyHP.setForeground(new java.awt.Color(0, 0, 0));
        pbEnemyHP.setValue(100);
        pbEnemyHP.setBorderPainted(false);
        pbEnemyHP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pbEnemyHP.setMaximumSize(new java.awt.Dimension(130, 10));
        pbEnemyHP.setMinimumSize(new java.awt.Dimension(130, 10));
        pbEnemyHP.setPreferredSize(new java.awt.Dimension(130, 10));
        pbEnemyHP.setStringPainted(true);
        pnlTLayout.add(pbEnemyHP);
        pbEnemyHP.setBounds(1080, 460, 130, 30);

        lblNameP.setFont(new java.awt.Font("Joystix Monospace", 0, 18)); // NOI18N
        lblNameP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameP.setText("Player");
        lblNameP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNameP.setMaximumSize(new java.awt.Dimension(110, 20));
        lblNameP.setMinimumSize(new java.awt.Dimension(110, 20));
        lblNameP.setPreferredSize(new java.awt.Dimension(110, 20));
        lblNameP.setRequestFocusEnabled(false);
        pnlTLayout.add(lblNameP);
        lblNameP.setBounds(260, 660, 110, 20);

        lblPlayerBorder.setBackground(new java.awt.Color(33, 28, 27));
        lblPlayerBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BattleUI_PlayerBorder.png"))); // NOI18N
        lblPlayerBorder.setName(""); // NOI18N
        pnlTLayout.add(lblPlayerBorder);
        lblPlayerBorder.setBounds(240, 500, 150, 150);

        lblPlayerAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PlaceHolder_PlayeAvatar.png"))); // NOI18N
        lblPlayerAvatar.setMaximumSize(new java.awt.Dimension(110, 110));
        lblPlayerAvatar.setMinimumSize(new java.awt.Dimension(110, 110));
        lblPlayerAvatar.setPreferredSize(new java.awt.Dimension(110, 110));
        pnlTLayout.add(lblPlayerAvatar);
        lblPlayerAvatar.setBounds(260, 520, 110, 110);

        lblHPBarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BattleUI_PlayerHP.png"))); // NOI18N
        pnlTLayout.add(lblHPBarP);
        lblHPBarP.setBounds(240, 460, 150, 32);

        pbPlayerHP.setBackground(new java.awt.Color(255, 255, 255));
        pbPlayerHP.setFont(new java.awt.Font("Joystix Monospace", 0, 10)); // NOI18N
        pbPlayerHP.setForeground(new java.awt.Color(0, 0, 0));
        pbPlayerHP.setValue(100);
        pbPlayerHP.setBorderPainted(false);
        pbPlayerHP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pbPlayerHP.setMaximumSize(new java.awt.Dimension(130, 10));
        pbPlayerHP.setMinimumSize(new java.awt.Dimension(130, 10));
        pbPlayerHP.setPreferredSize(new java.awt.Dimension(130, 10));
        pbPlayerHP.setStringPainted(true);
        pnlTLayout.add(pbPlayerHP);
        pbPlayerHP.setBounds(250, 460, 130, 30);

        btnAttack.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnAttack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI.png"))); // NOI18N
        btnAttack.setText("Attack");
        btnAttack.setContentAreaFilled(false);
        btnAttack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAttack.setMaximumSize(new java.awt.Dimension(100, 50));
        btnAttack.setMinimumSize(new java.awt.Dimension(100, 50));
        btnAttack.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAttack.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI_Pressed.png"))); // NOI18N
        btnAttack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI_Hovered.png"))); // NOI18N
        btnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttackActionPerformed(evt);
            }
        });
        pnlTLayout.add(btnAttack);
        btnAttack.setBounds(80, 460, 100, 50);

        btnDefend.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnDefend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI.png"))); // NOI18N
        btnDefend.setText("Defend");
        btnDefend.setContentAreaFilled(false);
        btnDefend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDefend.setMaximumSize(new java.awt.Dimension(100, 50));
        btnDefend.setMinimumSize(new java.awt.Dimension(100, 50));
        btnDefend.setPreferredSize(new java.awt.Dimension(100, 50));
        btnDefend.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI_Pressed.png"))); // NOI18N
        btnDefend.setRequestFocusEnabled(false);
        btnDefend.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI_Hovered.png"))); // NOI18N
        btnDefend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefendActionPerformed(evt);
            }
        });
        pnlTLayout.add(btnDefend);
        btnDefend.setBounds(80, 540, 100, 50);

        btnBag.setFont(new java.awt.Font("Joystix Monospace", 0, 12)); // NOI18N
        btnBag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI.png"))); // NOI18N
        btnBag.setText("Bag");
        btnBag.setContentAreaFilled(false);
        btnBag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBag.setMaximumSize(new java.awt.Dimension(100, 50));
        btnBag.setMinimumSize(new java.awt.Dimension(100, 50));
        btnBag.setPreferredSize(new java.awt.Dimension(100, 50));
        btnBag.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI_Pressed.png"))); // NOI18N
        btnBag.setRequestFocusEnabled(false);
        btnBag.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button_BattleUI_Hovered.png"))); // NOI18N
        btnBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagActionPerformed(evt);
            }
        });
        pnlTLayout.add(btnBag);
        btnBag.setBounds(80, 620, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BattleUI_InventoryUI.png"))); // NOI18N
        pnlTLayout.add(jLabel1);
        jLabel1.setBounds(420, 450, 620, 240);

        lblBattleUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BattleUI_Background_300.png"))); // NOI18N
        pnlTLayout.add(lblBattleUI);
        lblBattleUI.setBounds(0, 420, 1280, 300);

        lblPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Archer_Idle.gif"))); // NOI18N
        pnlTLayout.add(lblPlayer);
        lblPlayer.setBounds(50, 200, 256, 256);

        lblTutorialBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Tutorial_Background.png"))); // NOI18N
        pnlTLayout.add(lblTutorialBG);
        lblTutorialBG.setBounds(0, 0, 1280, 720);

        pnlTutorial.add(pnlTLayout, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTutorial);
        pnlTutorial.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        pnlMain.setVisible(false);
        //pnlChapter1Hallway.setVisible(true);
        //lblChapter1E.setVisible(true);
        //pnlIntro.setVisible(false);
        //pnlChapter1Elevator.setVisible(true);
        //lblChapter1Elevator.setVisible(true);
        //pnlIntro.setVisible(false);
        //pnlChapter2Elevator.setVisible(true);
        //pnlChapter2Hallway.setVisible(true);
        //lblChapter2Hallway1.setVisible(true);
        pnlChapter3Stair.setVisible(true);
        lblChapter2Hallway2.setVisible(true);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnHighScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoreActionPerformed
        // TODO add your handling code here:
        //pnlMain.setVisible(false);
        //pnlIntro.setVisible(true);
    }//GEN-LAST:event_btnHighScoreActionPerformed

    private void btnDefendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDefendActionPerformed

    private void btnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAttackActionPerformed

    private void btnBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBagActionPerformed

    private void btnPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlay1ActionPerformed
        // TODO add your handling code here:
        if(ctr==0){
            playMusic("C:\\Users\\Samuel\\Downloads\\Backgrounds-20240507T123957Z-001\\ost_1.wav");
            txtDialogue.setText("A blinding light.");
        }
        else if (ctr== 1){
            txtDialogue.setText("Their ruler, the alien king, proclaimed that they should rule all beings on earth.\nHumans opposed and it was not long till humanity was forced to fight \na battle for survival. ");
        }
        else if (ctr== 2){
            lblIntro2.setVisible(true);
            lblIntro1.setVisible(false);
            txtDialogue.setText("Three close adventurers, a Mage, a Shielder, and an Assassin found themselves at \nthe forefront of humanity's defense against the extraterrestrial menace. ");
        }
        else if (ctr== 3){
            txtDialogue.setText("The alien king, a formidable foe, led an army of minions. Despite being hailed as \nthe Strongest Party, the Adventurers realized they were severely outmatched.");
        }
        else if (ctr== 4){
            txtDialogue.setText("Faced with the impending doom, the trio took a desperate gamble.");
        }
        else if (ctr== 5){
            txtDialogue.setText("With a unified decision, they called upon the Goddess, \na mysterious entity rumored to possess the power to turn the tide \nagainst the alien invaders. ");
        }
        else if (ctr== 6){
            lblIntro3.setVisible(true);
            lblIntro2.setVisible(false);
            txtDialogue.setText("The Goddess appeared before them in a shimmering light,\nher eyes glowing with a celestial intensity.");
        }
        else if (ctr== 7){
            txtDialogue.setText("\"I can only grant one of you my blessing,\"");
        }
        else if (ctr== 8){
            txtDialogue.setText("her voice echoing through the desolate battlefield");
        }
        else if (ctr== 9){
            txtDialogue.setText("The Adventurer’s exchanged glances, understanding \nthe gravity of the choice before them");
        }
        else if (ctr== 10){
            txtDialogue.setText("The fate of Earth rested on the shoulders of the chosen hero.");
        }
        else if (ctr== 11){
            txtDialogue.setText("After a moment of tense deliberation, the Adventurer’s made their decision.");
        }
        else if (ctr== 12){
            txtDialogue.setText("The Goddess raised her hand, and a blinding light enveloped the chosen one");
        }
        else if (ctr== 13){
            lblIntro4.setVisible(true);
            lblIntro3.setVisible(false);
            txtDialogue.setText("The three heroes then set to battle the alien king.\nThe Mage, the Shielder and the Assassin, despite their \nbrilliance, fell in battle");
        }
        else if (ctr== 14){
            lblIntro5.setVisible(true);
            lblIntro4.setVisible(false);
            playMusic("");
            txtDialogue.setText("The world was plunged into darkness.");
        }
        else if (ctr== 15){
            Timer timer = new Timer(2000, e -> {
            txtDialogue.setText("10 Years Later...");
        });
        
        timer.setRepeats(false);
        timer.start();
            lblIntro6.setVisible(true);
            lblIntro5.setVisible(false);
        }
        else if (ctr== 16){
            
            txtDialogue.setText("True to the Goddess words. You have been reincarnated along with the \nskills you have been promised.");
        }
        else if (ctr== 17){
            txtDialogue.setText("The world is vastly different from what you know.");
        }
        else if (ctr== 18){
            txtDialogue.setText("Every structure you encounter is crumbling and everything was \nfilled with despair.");
        }
        else if (ctr== 19){
            txtDialogue.setText("Through the information you have gathered, you learned \nthat the Alien King has made the Tower of Hope its lair.");
        }
        else if (ctr== 20){
            txtDialogue.setText("As the newly reincarnated Hero, you set out on a venture to save the world.");
        }
        else if (ctr== 21){
            lblIntro7.setVisible(true);
            lblIntro6.setVisible(false);
            txtDialogue.setText("You reached the gates of the Tower of Hope. \nOnce a majestic monument, now a crumbling visage of what it once was.");
        }
        else if (ctr== 22){
            txtDialogue.setText("There is an enemy in formt of the gate");
        }
        else if (ctr== 23){
            lblAssassin.setVisible(true);
            lblIconAssassin.setVisible(true);
            txtDialogue.setText("A basic mob... good for a warm up");
            ctr=-1;
        }
        ctr++;
    }//GEN-LAST:event_btnPlay1ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(ctr==0){
            txtDialogue1.setText("You reached the hallway of the building. It is littered with dead bodies. ");
        }
        else if (ctr== 1){
            lblMonster.setVisible(true);
            txtDialogue1.setText("in the middle is another alien");
        }
        else if (ctr== 2){
            lblAssassin1.setVisible(true);
            lblMonster.setVisible(false);
            lblIconAssassin1.setVisible(true);
            txtDialogue1.setText("“Alien Scum”");
        }
        else if (ctr== 3){
            txtDialogue1.setText("You decided to engaged it!");
        }
        ctr++;
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
         if(ctr==0){
            lblAssassin2.setVisible(true);
            lblIconAssassin2.setVisible(true);
            txtDialogue2.setText("“I remember there were those devices installed in this building that uses levitating \nstones to traverse, elevators I think they were called.”");
        }
        else if (ctr== 1){
            lblMonster1.setVisible(true);
            lblAssassin2.setVisible(false);
            lblIconAssassin2.setVisible(false);
            txtDialogue2.setText("There is an alien blocking the way to the elevator");
        }
        else if (ctr== 2){
            lblAssassin2.setVisible(true);
            lblMonster1.setVisible(false);
            lblIconAssassin2.setVisible(true);
            txtDialogue2.setText("You spent minutes looking for other ways to pass, but there were none.");
        }
        else if (ctr== 3){
            txtDialogue2.setText("Swallowing your fear, you decided to face it head on!");
        }
        ctr++;
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        // TODO add your handling code here:
        if(ctr==0){
            txtDialogue3.setText("As you waited for the elevator to reach the top. \nThe memories of your comrades flashed back you begin to cry");
        }
        else if (ctr== 1){
            lblAssassin3.setVisible(true);
            txtDialogue3.setText("“*sob* God, these memories are from long ago', you said. \nWhy am i remembering these now”");
        }
        else if (ctr== 2){
            lblAssassin3.setVisible(false);
            txtDialogue3.setText("A sudden noise interrupts your reminiscing, followed \nby the sensation of the floor leaving your foot behind");
        }
        else if (ctr== 3){
            lblAssassin3.setVisible(true);
            txtDialogue3.setText("The elevator is falling apart. I need to get out of here");
        }
        else if (ctr== 4){
            lblAssassin3.setVisible(false);
            txtDialogue3.setText("You jumped out of the moving elevator into a floor \njust levels before the top floor");
        }
        else if (ctr== 5){
            lblChapter2Hallway.setVisible(true);
            lblChapter2Elevator.setVisible(false);
            txtDialogue3.setText("You lay there exhausted and tired. but you \nunderstood the responsibility the goddess has given you.");
        }
        else if (ctr== 6){
            txtDialogue3.setText("So you willed yourself to rise");
        }
        else if (ctr== 7){
            lblFamilliar.setVisible(true);
            txtDialogue3.setText("As you raise your head, a familiar visage stood \nbefore you");
        }
        else if (ctr== 8){
            lblShielderAlter.setVisible(true);
            lblFamilliar.setVisible(false);
            txtDialogue3.setText("It was your friend from a distant past, but there is something different about him.");
        }
        else if (ctr== 9){
            lblAssassin3.setVisible(true);
            lblShielderAlter.setVisible(false);
            txtDialogue3.setText("“Shielder… ... is that you? It's me! The Assassin!”");
        }
        else if (ctr== 10){
            lblShielderAlter.setVisible(true);
            lblAssassin3.setVisible(false);
            txtDialogue3.setText("But Shielder was only fixated on attacking you.");
        }
        else if (ctr== 11){
            
            txtDialogue3.setText("You dodged the barrage of attacks unleashed by your past friend.");
        }
        else if (ctr== 12){
            txtDialogue3.setText("It was then you noticed. The mark of the alien king on her facec.");
        }
        else if (ctr== 13){
            lblShielderAlterMark.setVisible(true);
            txtDialogue3.setText("");
        }
        else if (ctr== 14){
            txtDialogue3.setText("You realized your friend is gone.");
        }
        else if (ctr== 15){
            txtDialogue3.setText("What appears before you is nothing but a puppet, \na shell of your friend, being puppeteered by the evil alien king.");
        }
        else if (ctr== 16){
            lblShielderAlterMark.setVisible(false);
            txtDialogue3.setText("So you engaged her.");
        }
        
        ctr++;
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed
        if(ctr==0){
            txtDialogue4.setText("As your once ally laid there, another figure stepped in the shadow.");
        }
        else if (ctr== 1){
            lblMageAlter.setVisible(true);
            txtDialogue4.setText("");
        }
        else if (ctr== 2){
            txtDialogue4.setText("The once greatest Mage now branded with the alien kings seal.");
        }
        else if (ctr== 3){
            lblAssassin4.setVisible(true);
            lblMageAlter.setVisible(false);
            txtDialogue4.setText("You readied yourself, but then something unexpected happened.");
        }
        else if (ctr== 4){
            lblAssassin4.setVisible(false);
            txtDialogue4.setText("She spoke.");
        }
        else if (ctr== 5){
            lblMageAlter.setVisible(true);
            txtDialogue4.setText("Struggling, yes, but you can still make out the words.");
        }
        else if (ctr== 6){
            txtDialogue4.setText("“Assassin…end…me”");
        }
        else if (ctr== 7){
            txtDialogue4.setText("Your friend, even though under the spell of the alien king, \nkept on fighting all these years");
        }
        else if (ctr== 8){
            txtDialogue4.setText("“I...can't..stop..it...anymore”");
        }
        else if (ctr== 9){
            txtDialogue4.setText("Her withered soul pleaded for death.");
        }
        else if (ctr== 10){
            lblMageAlter.setVisible(false);
            lblAssassin4.setVisible(true);
            txtDialogue4.setText("Though it pains you, you granted your friends wish.");
        }
        ctr++;
    }//GEN-LAST:event_btnNext3ActionPerformed

    private void btnNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext4ActionPerformed
        if(ctr==0){
            txtDialogue5.setText("As your once ally laid there, another figure stepped in the shadow.");
        }
        else if (ctr== 1){
            lblMageAlter1.setVisible(true);
            txtDialogue5.setText("");
        }
        else if (ctr== 2){
            txtDialogue5.setText("The once greatest Mage now branded with the alien kings seal.");
        }
        else if (ctr== 3){
            lblAssassin5.setVisible(true);
            lblMageAlter1.setVisible(false);
            txtDialogue5.setText("You readied yourself, but then something unexpected happened.");
        }
        else if (ctr== 4){
            lblAssassin5.setVisible(false);
            txtDialogue5.setText("She spoke.");
        }
        else if (ctr== 5){
            lblMageAlter1.setVisible(true);
            txtDialogue5.setText("Struggling, yes, but you can still make out the words.");
        }
        else if (ctr== 6){
            txtDialogue5.setText("“Assassin…end…me”");
        }
        else if (ctr== 7){
            txtDialogue5.setText("Your friend, even though under the spell of the alien king, \nkept on fighting all these years");
        }
        else if (ctr== 8){
            txtDialogue5.setText("“I...can't..stop..it...anymore”");
        }
        else if (ctr== 9){
            txtDialogue5.setText("Her withered soul pleaded for death.");
        }
        else if (ctr== 10){
            lblMageAlter1.setVisible(false);
            lblAssassin5.setVisible(true);
            txtDialogue5.setText("Though it pains you, you granted your friends wish.");
        }
        ctr++;
    }//GEN-LAST:event_btnNext4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondWind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttack;
    private javax.swing.JButton btnBag;
    private javax.swing.JButton btnDefend;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHighScore;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnNext3;
    private javax.swing.JButton btnNext4;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlay1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAssassin;
    private javax.swing.JLabel lblAssassin1;
    private javax.swing.JLabel lblAssassin2;
    private javax.swing.JLabel lblAssassin3;
    private javax.swing.JLabel lblAssassin4;
    private javax.swing.JLabel lblAssassin5;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBattleUI;
    private javax.swing.JLabel lblChapter1E;
    private javax.swing.JLabel lblChapter1Elevator;
    private javax.swing.JLabel lblChapter2Elevator;
    private javax.swing.JLabel lblChapter2Hallway;
    private javax.swing.JLabel lblChapter2Hallway1;
    private javax.swing.JLabel lblChapter2Hallway2;
    private javax.swing.JLabel lblChapter2Stairs;
    private javax.swing.JLabel lblColumnL;
    private javax.swing.JLabel lblColumnR;
    private javax.swing.JLabel lblDialogueBox;
    private javax.swing.JLabel lblDialogueBox1;
    private javax.swing.JLabel lblDialogueBox2;
    private javax.swing.JLabel lblDialogueBox3;
    private javax.swing.JLabel lblDialogueBox4;
    private javax.swing.JLabel lblDialogueBox5;
    private javax.swing.JLabel lblEnemyAvatar;
    private javax.swing.JLabel lblEnemyBorder;
    private javax.swing.JLabel lblFamilliar;
    private javax.swing.JLabel lblHPBarE;
    private javax.swing.JLabel lblHPBarP;
    private javax.swing.JLabel lblIconAssassin;
    private javax.swing.JLabel lblIconAssassin1;
    private javax.swing.JLabel lblIconAssassin2;
    private javax.swing.JLabel lblIntro1;
    private javax.swing.JLabel lblIntro2;
    private javax.swing.JLabel lblIntro3;
    private javax.swing.JLabel lblIntro4;
    private javax.swing.JLabel lblIntro5;
    private javax.swing.JLabel lblIntro6;
    private javax.swing.JLabel lblIntro7;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblMageAlter;
    private javax.swing.JLabel lblMageAlter1;
    private javax.swing.JLabel lblMonster;
    private javax.swing.JLabel lblMonster1;
    private javax.swing.JLabel lblNameE;
    private javax.swing.JLabel lblNameP;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerAvatar;
    private javax.swing.JLabel lblPlayerBorder;
    private javax.swing.JLabel lblShielderAlter;
    private javax.swing.JLabel lblShielderAlterMark;
    private javax.swing.JLabel lblTutorialBG;
    private javax.swing.JProgressBar pbEnemyHP;
    private javax.swing.JProgressBar pbPlayerHP;
    private javax.swing.JPanel pnlChapter1Elevator;
    private javax.swing.JPanel pnlChapter1Hallway;
    private javax.swing.JPanel pnlChapter2Elevator;
    private javax.swing.JPanel pnlChapter2Hallway;
    private javax.swing.JPanel pnlChapter3Stair;
    private javax.swing.JPanel pnlIntro;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTLayout;
    private javax.swing.JPanel pnlTutorial;
    private javax.swing.JTextArea txtDialogue;
    private javax.swing.JTextArea txtDialogue1;
    private javax.swing.JTextArea txtDialogue2;
    private javax.swing.JTextArea txtDialogue3;
    private javax.swing.JTextArea txtDialogue4;
    private javax.swing.JTextArea txtDialogue5;
    // End of variables declaration//GEN-END:variables
}
